version: '3.1'

services:

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      # - __WEB_PORT__:8000
      - 8080:8080

    env_file:
      - ./docker.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
