version: '3.1'

services:

  web:
    build:
      context: .
    container_name: PBL7-backend
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./docker.env

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command:
      - ngrok config add-authtoken 2QjcBSc1a8mdClgelHJaZXiXeh1_6S4DBgVfMRyHj8eQPCrS
      - ngrok http web:8000
    ports:
      - 4040:4040
