version: '3.1'

services:
  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    restart: always
    ports:
      - 4040:4040
    environment:
      NGROK_CONFIG: /ngrok/ngrok.yml
    volumes:
      - ./ngrok.yml:/ngrok/ngrok.yml
    depends_on:
      - web

  web:
    build:
      context: .
    container_name: PBL7-backend
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./docker.env
