version: '3.1'

services:

  web:
    build:
      context: .
    container_name: PBL7-backend
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./docker.env

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command: ngrok http web:8000
    environment:
      - NGROK_AUTHTOKEN=2hV2ShD4AqMNUw6fezwwVTx44cK_4mPJ6YUR6qYJfg6GUyQvp
    ports:
      - 4040:4040
