# Generated by Django 5.0.3 on 2024-05-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_name', models.CharField(max_length=255)),
                ('reviews_count', models.IntegerField()),
                ('general_info', models.TextField()),
                ('summary', models.TextField()),
                ('reviews', models.JSONField()),
                ('star_ratings', models.JSONField()),
                ('location', models.JSONField()),
                ('reviews_time', models.JSONField()),
            ],
        ),
    ]
