# Generated by Django 5.0.3 on 2024-06-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0002_alter_attraction_general_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='review_count_non_calc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='attraction',
            table='attractions',
        ),
    ]
