# Generated by Django 5.0.3 on 2024-05-18 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_message', models.TextField()),
                ('system_answer', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_from_system', models.BooleanField(default=False)),
                ('descriptions', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chathistories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_history',
            },
        ),
    ]
